### ISSUE TITLE
Reader Comments

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/rwxrob#3]
Add your comments and reactions to anything I've written or done here. The fact that you have to have GitHub account means that I don't have to worry about the quality of the comments made (unlike other platforms and forums).

**Comment by ivanvgav** [comment]
Hi Rob! Thanks for everything you do and have done until now.

I would to suggest if you take advantage of the discussions feature here in github. I think it would be better at least for your projects such as the books and the boost. It seems to me that is a good separation of concerns and help to understand better to beginners like myself the purpose of an issue in a github repo.

Greetings from Argentina!

**Comment by rwxrob** [comment]
Great idea. Let's close this one. Discussion is open now.
